# Generated by Django 3.2.5 on 2021-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_todo_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
